### ISSUE TITLE
suspicious of dp/px

### ISSUE THREAD

**Issue by derekdreery** [linebender/glazier#26]
I think that sometimes we are returning measurements in device points when we should be using physical pixels, and vice versa. winit use some newtype wrappers to make the two types of measurement distinct in the type system. Whether we copy this or not, we should audit the places that take or return measurements to make sure they are using the right units.

As a specific example, I think `WindowHandle::get_size` is returning physical pixels when the docs say device points.

**Comment by raphlinus** [comment]
I poked at this just a little, focusing on the mac backend (it may well be that Windows works better). I believe the culprit is the mac backend implementation of [get_scale](https://github.com/linebender/glazier/blob/main/src/backend/mac/window.rs#L1387), which has a TODO and just returns 1.0 for dpi scaling. This is not a glazier-specific problem, the code is the same as druid-shell. I believe the most likely explanation is that druid-shell also gets the dpi scale factor wrong, but then the Core Graphics back-end for piet applies the correct scale factor for rasterization, so it doesn't matter much.

**Comment by leontepe** [comment]
Is there agreement on generally moving to newtypes for these units though? To encode this information in the type system and avoid these kind of errors?

**Comment by leontepe** [comment]
So these aren't equivalent to `winit`'s [`LogicalSize`](https://github.com/rust-windowing/winit/blob/05484c5888ea598c3920cb7d43e7f581ffe7f071/src/dpi.rs#L330) and [`PhysicalSize`](https://github.com/rust-windowing/winit/blob/05484c5888ea598c3920cb7d43e7f581ffe7f071/src/dpi.rs#L412)?

**Comment by raphlinus** [comment]
If we did newtypes for size in display points and hardware pixels, they would be basically equivalent to the winit types, but I don't think it's worth it.

**Comment by raphlinus** [comment]
I was also experimenting with Windows, and dpi scaling has issues there as well. As far as I can tell, the value reported to the `WinHandler::size()` callback is correctly in display points, but `WindowHandle::get_size()` is actually returning hardware pixels (see [comment](https://github.com/linebender/glazier/blob/a100529e09250e321dd5247219a2a7952d38a7bc/src/backend/windows/window.rs#L1701) on backend impl). This was introduced in https://github.com/linebender/druid/pull/1713, where some of the methods were updated but `get_size` was skipped. I think Druid doesn't actually use `get_size`, but the xilem prototype does. (This is also perhaps something we should reconsider, arguably the configuration of render resources should be edge-triggered by a `size()` callback rather than level-triggered, but either way the call should do what it says)

One last thing. I think it's highly confusing that we use "px" for hardware pixels, while in CSS the "px" identifier means the same concept we're calling "display points." I'm ok with "dp" because at least it's consistent with Android, but I suggest we use "pxl" or "pixel" instead.

**Comment by raphlinus** [comment]
Now that #36 has landed, I'm wondering whether this can be closed. I'm not sure things are perfect (particularly in the dynamic case), but I think we have parity with the Druid state.

**Comment by derekdreery** [comment]
Yes let's close - I'll open something more specific if I continue to get issues.
